### ISSUE TITLE
non-ASCII characters in codebox throw exception

### ISSUE THREAD

**Issue by lulezi** [danielecook/codebox-alfred#2]
As soon as there is a non-ASCII character (i.e. ü) in any of the snippets, the `ff [search]` command fails (see screenshot).

<img width="611" alt="screen shot 2016-10-28 at 12 06 55" src="https://cloud.githubusercontent.com/assets/870062/19808654/1c577a2a-9d26-11e6-9788-277bee29b8e8.png">

I've narrowed the error down to workflow/workflow.py:478 in the `isascii` method. But as I'm not very familiar with python, I wasn't able to fix the issue.

**Comment by danielecook** [comment]
Thanks for bringing this to my attention - I will try to resolve this soon.

**Comment by danielecook** [comment]
Better late than never... This should now be fixed with 1e53332
