### ISSUE TITLE
uncheck hide extension on Codebox library file

### ISSUE THREAD

**Issue by Onslaught** [danielecook/codebox-alfred#4]
I think it's important to note that you have to un-hide the extensions or Alfred won't find the file. 
<img width="395" alt="screen shot 2018-01-30 at 3 02 12 pm" src="https://user-images.githubusercontent.com/2284746/35588598-225e6ee8-05cf-11e8-9a40-d38397cbe52d.png">

**Comment by danielecook** [comment]
added a note to the readme.
